[package]
name = "air-gradient-pro-rs"
description = "Rust firmware for the AirGradient Pro"
version = "0.1.0"
edition = "2021"
authors = ["Jon Lamb"]
build = "build.rs"

[[bin]]
name = "air-gradient-pro"
path = "src/entry.rs"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
rtic-monotonic = "1.0"
cortex-m-rtic = "1.1"
log = "0.4"
ds323x = "0.5"
sh1106 = "0.4"

[dependencies.wire-protocols]
path = "libraries/wire-protocols"

# TODO - upstream these changes
[dependencies.sgp41]
#sgp41 = "0.1"
git = "https://github.com/jonlamb-gh/sgp41.git"
branch = "various-changes"

# TODO - use crates.io once available
[dependencies.sht3x]
git = "https://github.com/miek/sht3x-rs.git"
branch = "master"

[dependencies.stm32f4xx-hal]
version = "0.15"
features = ["rt", "stm32f411", "rtic"]

[dependencies.smoltcp]
version = "0.9"
default-features = false
features = [
    "medium-ethernet",
    "medium-ip",
    "proto-ipv4",
    "socket-icmp",
    "socket-udp",
    "socket-tcp",
    #"log",
    #"verbose"
]

[dependencies.enc28j60]
git = "https://github.com/jonlamb-gh/enc28j60.git"
branch = "cleanup"

[dependencies.embedded-graphics]
version = "0.7"
default-features = false

[dependencies.shared-bus]
version = "0.2"
default-features = false
features = ["cortex-m"]

[build-dependencies.built]
version = "0.5"
features = ["git2", "chrono"]

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations

[package.metadata.renode]
machine-name = 'agp-machine'
using-sysbus = true
#renode = '${HOME}/repos/forks/renode/renode'
variables = [
    '$tap ?= "renode-tap0"',
]
platform-description = '''
using "platforms/cpus/stm32f412.repl"

led: Miscellaneous.LED @ gpioPortC

gpioPortC:
    13 -> led@0

ethernet: Network.ENC28J60 @ spi2i2s2
    -> gpioPortA@8

ds3231 : Sensors.DS3231 @ i2c1 0x68

sh1106 : Video.SH1106 @ i2c2 0x3C
    FramesPerVirtualSecond: 10

sgp41 : Sensors.SGP41 @ i2c2 0x59
    VocTicks: 1024
    NoxTicks: 2048

sht31 : Sensors.SHT31 @ i2c2 0x44
    Temperature: 40
    Humidity: 85
'''
pre-start-commands = [
    'cpu PerformanceInMips 1',
    'showAnalyzer sysbus.usart2',
    'showAnalyzer i2c2.sh1106',
    '''
    sysbus.usart2 AddLineHook "PANIC" "Antmicro.Renode.Logging.Logger.Log(LogLevel.Error, line)"
    sysbus.usart2 AddLineHook "test result: ok" "Antmicro.Renode.Emulator.Exit()"
    ''',
    '''
    emulation CreateSwitch "switch"
    connector Connect spi2i2s2.ethernet switch
    emulation CreateTap $tap "tap"
    connector Connect host.tap switch
    ''',
]
reset = 'sysbus LoadELF $bin'
