[package]
name = "air-gradient-pro-rs"
version = "0.1.0"
edition = "2021"
authors = ["Jon Lamb"]
build = "build.rs"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
rtic-monotonic = "1.0"
cortex-m-rtic = "1.1"
log = "0.4"
modular-bitfield = "0.11"
ieee802_3_miim = "0.8"
ds323x = "0.5"

[dependencies.stm32f4xx-hal]
version = "0.14"
features = ["rt", "stm32f429", "rtic"]

[dependencies.stm32-eth]
version = "0.4"
default-features = false
features = ["stm32f429", "smoltcp-phy"]

[dependencies.smoltcp]
version = "0.8"
default-features = false
features = [
    "medium-ethernet",
    "medium-ip",
    "proto-ipv4",
    "socket-icmp",
    "socket-udp",
    "socket-tcp",
    #"log",
    #"verbose"
]

[build-dependencies.built]
version = "0.5"
features = ["git2", "chrono"]

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
