[toolchain]
channel = "stable"
components = ["rustfmt", "clippy", "llvm-tools-preview"]
targets = ["thumbv7em-none-eabihf", "x86_64-unknown-linux-gnu", "aarch64-unknown-linux-musl"]
profile = "minimal"
