name: Development Artifacts

# TODO - surface choice for max log level
on:
  workflow_dispatch:
    inputs:
      ip_address:
        description: 'Sets the build env var AIR_GRADIENT_IP_ADDRESS'
        type: string
        required: false
      mac_address:
        description: 'Sets the build env var AIR_GRADIENT_MAC_ADDRESS'
        type: string
        required: false
      device_id:
        description: 'Sets the build env var AIR_GRADIENT_DEVICE_ID'
        type: string
        required: false
      broadcast_port:
        description: 'Sets the build env var AIR_GRADIENT_BROADCAST_PORT'
        type: string
        required: false
      broadcast_address:
        description: 'Sets the build env var AIR_GRADIENT_BROADCAST_ADDRESS'
        type: string
        required: false
      device_port:
        description: 'Sets the build env var AIR_GRADIENT_DEVICE_PORT'
        type: string
        required: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build_fw:
    name: Build Embedded
    runs-on: ubuntu-latest
    strategy:
      matrix:
        binary: [firmware, bootloader]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain and components
        run: rustup component add rustfmt clippy llvm-tools-preview

      - name: Install binutils, flip-link
        run: cargo install cargo-binutils flip-link

      - name: Setup environment variable 'AIR_GRADIENT_IP_ADDRESS'
        if: "${{ github.event.inputs.ip_address != '' }}"
        run: |
          AIR_GRADIENT_IP_ADDRESS=${{ github.event.inputs.ip_address }}
          echo "AIR_GRADIENT_IP_ADDRESS=$AIR_GRADIENT_IP_ADDRESS"
          echo AIR_GRADIENT_IP_ADDRESS=${AIR_GRADIENT_IP_ADDRESS} >> $GITHUB_ENV

      - name: Setup environment variable 'AIR_GRADIENT_MAC_ADDRESS'
        if: "${{ github.event.inputs.mac_address != '' }}"
        run: |
          AIR_GRADIENT_MAC_ADDRESS=${{ github.event.inputs.mac_address }}
          echo "AIR_GRADIENT_MAC_ADDRESS=$AIR_GRADIENT_MAC_ADDRESS"
          echo AIR_GRADIENT_MAC_ADDRESS=${AIR_GRADIENT_MAC_ADDRESS} >> $GITHUB_ENV

      - name: Setup environment variable 'AIR_GRADIENT_DEVICE_ID'
        if: "${{ github.event.inputs.device_id != '' }}"
        run: |
          AIR_GRADIENT_DEVICE_ID=${{ github.event.inputs.device_id }}
          echo "AIR_GRADIENT_DEVICE_ID=$AIR_GRADIENT_DEVICE_ID"
          echo AIR_GRADIENT_DEVICE_ID=${AIR_GRADIENT_DEVICE_ID} >> $GITHUB_ENV

      - name: Setup environment variable 'AIR_GRADIENT_BROADCAST_PORT'
        if: "${{ github.event.inputs.broadcast_port != '' }}"
        run: |
          AIR_GRADIENT_BROADCAST_PORT=${{ github.event.inputs.broadcast_port }}
          echo "AIR_GRADIENT_BROADCAST_PORT=$AIR_GRADIENT_BROADCAST_PORT"
          echo AIR_GRADIENT_BROADCAST_PORT=${AIR_GRADIENT_BROADCAST_PORT} >> $GITHUB_ENV

      - name: Setup environment variable 'AIR_GRADIENT_BROADCAST_ADDRESS'
        if: "${{ github.event.inputs.broadcast_address != '' }}"
        run: |
          AIR_GRADIENT_BROADCAST_ADDRESS=${{ github.event.inputs.broadcast_address }}
          echo "AIR_GRADIENT_BROADCAST_ADDRESS=$AIR_GRADIENT_BROADCAST_ADDRESS"
          echo AIR_GRADIENT_BROADCAST_ADDRESS=${AIR_GRADIENT_BROADCAST_ADDRESS} >> $GITHUB_ENV

      - name: Setup environment variable 'AIR_GRADIENT_DEVICE_PORT'
        if: "${{ github.event.inputs.device_port != '' }}"
        run: |
          AIR_GRADIENT_DEVICE_PORT=${{ github.event.inputs.device_port }}
          echo "AIR_GRADIENT_DEVICE_PORT=$AIR_GRADIENT_DEVICE_PORT"
          echo AIR_GRADIENT_DEVICE_PORT=${AIR_GRADIENT_DEVICE_PORT} >> $GITHUB_ENV

      - name: Build release binary
        working-directory: ${{ matrix.binary }}
        run: cargo build --release

      - name: Print firmware size
        working-directory: ${{ matrix.binary }}
        run: |
          cargo size --release
          echo '## Firmware size' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cargo size --release >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Prepare artifacts
        if: "${{ matrix.binary == 'firmware' }}"
        run: |
          mkdir -p artifacts
          cp firmware/target/thumbv7em-none-eabihf/release/air-gradient-pro artifacts/air-gradient-pro

      - name: Prepare artifacts
        if: "${{ matrix.binary == 'bootloader' }}"
        run: |
          mkdir -p artifacts
          cp bootloader/target/thumbv7em-none-eabihf/release/bootloader artifacts/bootloader

      - name: Upload artifacts
        if: "${{ matrix.binary == 'firmware' }}"
        uses: actions/upload-artifact@v3
        with:
          name: air-gradient-artifacts-${{ github.sha }}
          if-no-files-found: error
          retention-days: 2
          path: |
            artifacts/air-gradient-pro

      - name: Upload artifacts
        if: "${{ matrix.binary == 'bootloader' }}"
        uses: actions/upload-artifact@v3
        with:
          name: air-gradient-artifacts-${{ github.sha }}
          if-no-files-found: error
          retention-days: 2
          path: |
            artifacts/bootloader

  build_cli:
    name: Build CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain and components
        run: rustup component add rustfmt clippy

      - name: Install aarch64 toolchains
        run: |
          sudo apt-get install gcc-aarch64-linux-gnu

          sudo mkdir -p /usr/local/src /usr/local/bin
          sudo wget --no-verbose --quiet https://musl.cc/aarch64-linux-musl-cross.tgz -O /usr/local/src/aarch64-linux-musl-cross.tgz
          sudo tar -xf /usr/local/src/aarch64-linux-musl-cross.tgz -C /usr/local/bin/
          echo CC_aarch64_unknown_linux_musl=/usr/local/bin/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc >> $GITHUB_ENV

      - name: Build release CLI for x86_64-unknown-linux-gnu
        run: cargo build --release --target x86_64-unknown-linux-gnu --features "native-tls" --no-default-features
        working-directory: host_tools/air-gradient-cli

      - name: Build release CLI for aarch64-unknown-linux-musl
        run: cargo build --release --target aarch64-unknown-linux-musl --features "rustls" --no-default-features
        working-directory: host_tools/air-gradient-cli

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp host_tools/air-gradient-cli/target/x86_64-unknown-linux-gnu/release/air-gradient artifacts/air-gradient-x86_64
          cp host_tools/air-gradient-cli/target/aarch64-unknown-linux-musl/release/air-gradient artifacts/air-gradient-aarch64

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: air-gradient-artifacts-${{ github.sha }}
          if-no-files-found: error
          retention-days: 2
          path: |
            artifacts/air-gradient-x86_64
            artifacts/air-gradient-aarch64
